modules:
    app:
        handler: file
        processor: web
        format: ltsv
        path: %APPPATH%/logs/app
        # Log level
        #   100: debug
        #   200: info
        #   250: notice
        #   300: warning
        #   400: error
        #   500: critical
        #   550: alert
        #   600: emergency
        level: 100
    sql:
        handler: file
        processor: sql
        format: ltsv
        path: %APPPATH%/logs/sql
        level: 100
    task:
        handler: file
        processor: task
        format: ltsv
        path: %APPPATH%/logs/task
        level: 100
